feat: system backup function

diff --git a/bash_aliases/sysquickcalls b/bash_aliases/sysquickcalls
--- a/bash_aliases/sysquickcalls
+++ b/bash_aliases/sysquickcalls
@@ -25,3 +25,71 @@ alias netstatl='sudo netstat -tulpn'  # List all listening ports
 alias cpuinfo='lscpu'
 alias meminfo='free -h'
 alias diskinfo='df -h'
+
+# System admin functions
+
+backup_system() {
+	local dir_to_backup="/"
+	local backup_destination="/opt/backup"
+	local backup_log="/var/log"
+
+	RESET='\033[0m'
+	RED='\033[0;31m'
+	GREEN='\033[0;32m'
+	YELLOW='\033[0;33m'
+	BLUE='\033[0;34m'
+
+	log() {
+		local level="$1"
+		local message="$2"
+		local color="$3"
+		echo -e "$(date +'%Y-%m-%d %H:%M:%S') [${color}${level}${RESET}]: ${color}${message}${RESET}" \
+			| tee -a "$backup_log/$(date +'%Y-%m-%d %H')_$level_system_backup.log"
+	}
+
+	create_backup() {
+		#log debug "Creating directory structure as needed" "$BLUE"
+		mkdir -p "$backup_destination" || {
+			log error "Failed to create backup directory." "$RED" 
+		}
+
+		local backup_file="$backup_destination/backup_$(date +"%Y%m%d_%H%M%S").tar.gz"
+
+		#log debug "Starting the system backup" "$BLUE"
+		tar -cvpzf "$backup_file" \
+			--exclude="$backup_file" \
+			--exclude=/boot \
+			--exclude=/opt \
+			--exclude=/proc \
+			--exclude=/tmp \
+			--exclude=/mnt \
+			--exclude=/dev \
+			--exclude=/sys \
+			--exclude=/srv \
+			--exclude=/run \
+			--exclude=/lib \
+			--exclude=/media \
+			--exclude=/var \
+			--exclude=/usr \
+			--exclude=/bin \
+			--exclude=/sbin \
+			--exclude=/lost+found \
+			--exclude=/home \
+			--exclude=/root \
+			--one-file-system \
+			--acls \
+			--xattrs \
+			"$dir_to_backup" || {
+				log error "Failed to create backup." "$RED" 
+			}
+
+		log success "Backup created successfully: $backup_file" "$GREEN" 
+
+	}
+
+	create_backup || {
+		log error "Backup folder creation failed..." "$RED"
+	}
+}
+
+
